language: scala
scala:
- 2.11.2
- 2.12.2
script:
- sbt ++$TRAVIS_SCALA_VERSION test
deploy:
  provider: heroku
  api_key:
    secure: gKXBrqWxnrnSX/6lY4/9XxlmytCCL9LRJ0mH+xGTCQHd9ImLmxR0B4K9j3REMgobDWxxRIX3PJ22kgQXtHIfy0ZetViDF2EtlXoaZrwk/t502cS43Zz9eP9HGqudNfIy2hFpNn/ZomAtYOAyaeqLAKSZe23PET5uxIpSmyEnetVIBzEbCk8ANB7CA1aNYpYN9IyiID5V/xJzGY12aS9Wh7LqpAP345cl02EBQNq+tPMPuOTJ/ABD+LIljqNwkiF9PNRasliOUoHbvAeUWGe9kB6OUmLhvQ6k79thoI9psjDBzH+QI13ByPBARL0j7CQ3zLxwqYxe5JjQxi8BhKSaVTZNfKR4kFwgqVnas1Ikkq1L7duqTveMd2w4TfzTGxBYLmYhNG+XoVCmoWQtI4pDZRcEy+EKgzKhLIEaSEyCtnz08+MF0FKSnswfAt9PykCw369joCav8JQwt/AnnBEg7rZRZVLHXe875EPQLR4alrTogYrNeuC3dXgF4Yr6LM5rTkl5myRg05Nkzlh77jV/0X6AelW4LmIQ8I153x6VnQKAvSKobmsBGFr90kq0RNnARcxow2QjsRULh7L2uKih94yaf1t+rcsyN3gsVY9hAb0D+VCRYvC87/lMwSDkyWMB2hxr/waHz8X/TP1F2dkhYt8vRb05IL7q21I2yEpY2Vg=
  on: master
